lang: ko
title: 잡것들
author: yjk
email: sto998@nate.com
description: >- # this means to ignore newlines until "baseurl:"
  이것저것 잡다구리.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jinikr.github.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jinikr
rss: rss

# Build settings
markdown: kramdown
theme: tale

permalink:  /:year-:month-:day/:title
paginate:   2

google_analytics: UA-NNNNNNNN-N
